- name: Create RDP User and Configure Session
        run: |
          # Kredensial User
          RDP_USER="debianuser"
          RDP_PASS="YourSecurePasswordHere" # Ganti dengan password yang kuat!
          
          # Tambahkan user baru dan berikan password
          sudo useradd -m $RDP_USER -s /bin/bash
          echo "$RDP_USER:$RDP_PASS" | sudo chpasswd
          
          # Tambahkan user ke grup yang dibutuhkan
          sudo usermod -aG sudo $RDP_USER
          sudo usermod -aG ssl-cert $RDP_USER
          
          # --- KONFIGURASI XFCE UNTUK XRDP ---
          # 1. Buat direktori konfigurasi .xsession di home directory pengguna
          echo "startxfce4" > /home/$RDP_USER/.xsession
          
          # 2. Pastikan izinnya benar
          sudo chmod +x /home/$RDP_USER/.xsession
          sudo chown $RDP_USER:$RDP_USER /home/$RDP_USER/.xsession

          # 3. AKTIFKAN LAYANAN XRDP (Hapus baris ini dari langkah sebelumnya jika ada)
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          
          # Tampilkan kredensial user untuk RDP
          echo "::notice file=README.md,line=1::RDP USER: $RDP_USER"
          echo "::notice file=README.md,line=2::RDP PASSWORD: $RDP_PASS"
