name: RDP_DEBIAN_STYLE_TAILSCALE

on:
  workflow_dispatch:

jobs:
  secure-rdp-debian:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Update System and Install XFCE/XRDP
        run: |
          sudo apt update -y
          sudo apt install -y xrdp xfce4 xfce4-goodies
          
      - name: Create RDP User and Configure Session
        run: |
          # Kredensial User
          RDP_USER="debianuser"
          RDP_PASS="YourSecurePasswordHere" # Ganti dengan password yang kuat!
          
          # 1. Tambahkan user baru dan berikan password (Hanya perlu sekali 'sudo')
          sudo useradd -m $RDP_USER -s /bin/bash
          echo "$RDP_USER:$RDP_PASS" | sudo chpasswd
          
          # 2. Tambahkan user ke grup
          sudo usermod -aG sudo $RDP_USER
          sudo usermod -aG ssl-cert $RDP_USER
          
          # 3. Konfigurasi XRDP agar menggunakan XFCE
          # Buat file .xsession di home directory pengguna dan pastikan kepemilikannya benar
          echo "xfce4-session" | sudo tee /home/$RDP_USER/.xsession > /dev/null
          sudo chmod +x /home/$RDP_USER/.xsession
          sudo chown $RDP_USER:$RDP_USER /home/$RDP_USER/.xsession

          # 4. Aktifkan dan jalankan layanan XRDP
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          
          # 5. Tampilkan kredensial user untuk RDP
          echo "::notice file=README.md,line=1::RDP USER: $RDP_USER"
          echo "::notice file=README.md,line=2::RDP PASSWORD: $RDP_PASS"

      - name: Install and Configure Tailscale
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          curl -fsSL https://tailscale.com/install.sh | sudo sh
          
          sudo tailscale up --authkey=$TAILSCALE_AUTH_KEY --hostname="github-debian-rdp-${{ github.run_id }}" --accept-routes=true
          
          TAILSCALE_IP=$(sudo tailscale ip -4)
          echo "::notice file=README.md,line=3::TAILSCALE IP ADDRESS: $TAILSCALE_IP"
          
      - name: Keep Runner Alive (6 Hours)
        run: |
          echo "RDP is ready. Waiting for 6 hours before system timeout."
          sleep 21600
          
      - name: End Job
        if: always()
        run: echo "Workflow finished."
