name: RDP_LINUX_TAILSCALE

on:
  # Mengizinkan menjalankan workflow secara manual dari Actions tab di GitHub
  workflow_dispatch:

jobs:
  secure-rdp-linux:
    # Menggunakan runner Ubuntu Linux terbaru
    runs-on: ubuntu-latest
    # Menentukan waktu maksimal (6 jam)
    timeout-minutes: 360

    steps:
      - name: Update System and Install Dependencies
        run: |
          # Perbarui sistem
          sudo apt update -y
          
          # Instal dependencies, XRDP untuk Remote Desktop, dan lingkungan desktop XFCE
          sudo apt install -y xrdp xfce4 xfce4-goodies
          
          # Tambahkan user 'github' dan berikan password
          sudo useradd -m github -s /bin/bash
          echo "github:YourSecurePasswordHere" | sudo chpasswd
          
          # Tambahkan user 'github' ke grup sudo agar bisa menjalankan perintah root
          sudo usermod -aG sudo github

          # Konfigurasi XRDP agar menggunakan XFCE
          echo xfce4-session > ~/.xsession
          sudo mv ~/.xsession /home/github/.xsession
          sudo chown github:github /home/github/.xsession

          # Aktifkan dan jalankan layanan XRDP
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          
          # Tampilkan kredensial user untuk RDP
          echo "::notice file=README.md,line=1::RDP USER: github"
          echo "::notice file=README.md,line=2::RDP PASSWORD: YourSecurePasswordHere"
          
      - name: Install and Configure Tailscale
        env:
          # Mengambil Tailscale Auth Key dari GitHub Secrets
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          # 1. Tambahkan repositori resmi Tailscale (menggunakan skrip instalasi)
          curl -fsSL https://tailscale.com/install.sh | sh
          
          # 2. Jalankan Tailscale menggunakan Auth Key
          sudo tailscale up --authkey=$TAILSCALE_AUTH_KEY --hostname="github-linux-rdp-${{ github.run_id }}" --accept-routes=true
          
          # 3. Tampilkan IP Tailscale untuk koneksi
          TAILSCALE_IP=$(sudo tailscale ip -4)
          echo "::notice file=README.md,line=3::TAILSCALE IP ADDRESS: $TAILSCALE_IP"
          
      - name: Wait for Tailscale IP Assignment (360 Minutes)
        run: |
          # Langkah menunggu agar RDP tetap aktif selama 6 jam (sesuai timeout-minutes)
          echo "RDP is ready. Waiting for 360 minutes before system timeout."
          sleep 21600 # 360 menit x 60 detik = 21600 detik
          
      # Hentikan runner setelah waktu tunggu berakhir
      - name: End Job
        if: always()
        run: echo "Workflow finished."
