name: Deploy Aplikasi ke VPS

# Kontrol kapan workflow ini akan berjalan
on:
# ... (Event push dan workflow_dispatch tetap sama)

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4

      # --- DIAGNOSTIK: Uji Koneksi SSH ---
      - name: Uji Koneksi SSH (Ping Sederhana)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          # Perintah sederhana untuk menguji apakah koneksi terbuat
          script: |
            echo "Koneksi SSH berhasil! Host: $SSH_HOST"
            
      # ----------------------------------------------------
      # 2. Sinkronisasi File (Deployment)
      # ----------------------------------------------------
      # Ubah SCP ke rsync yang lebih andal untuk sync
      - name: Sinkronisasi File ke VPS via Rsync
        uses: burnettk/rsync-action@main
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "." 
          target: ${{ secrets.DEPLOY_DIR }}

      # ----------------------------------------------------
      # 3. Jalankan Perintah Deployment
      # ----------------------------------------------------
      - name: Jalankan Perintah Setelah Deployment
        uses: appleboy/ssh-action@v1.0.3
        # ... (sisa konfigurasi sama)
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22 
          script: |
            # ... (perintah pasca-deploy Anda)
            echo "Perintah pasca-deploy selesai."
