name: Deploy n8n via Docker Compose

on:
  push:
    # Jalankan saat ada push ke branch 'main'
    branches:
      - main
    # Opsional: Jika Anda hanya ingin deploy saat ada perubahan di folder Docker
    # paths:
    #   - 'docker/**'
    #   - 'docker-compose.yml'
  
  # Memberikan opsi untuk menjalankan workflow secara manual dari tab Actions
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4

      # ----------------------------------------------------
      # Langkah 1: Transfer file Docker Compose ke VPS
      # ----------------------------------------------------
      - name: Transfer Docker Compose File via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          # Direktori sumber (source): file di GitHub repo yang ingin dikirim
          source: "docker-compose.yml" 
          # Direktori tujuan (target): di VPS
          target: ${{ secrets.DEPLOY_DIR }}

      # ----------------------------------------------------
      # Langkah 2: Update dan Restart n8n di VPS
      # ----------------------------------------------------
      - name: Update dan Restart n8n via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22 
          # Perintah yang dijalankan di dalam VPS
          script: |
            echo "Memulai update n8n..."
            
            # Pindah ke direktori deployment n8n
            cd ${{ secrets.DEPLOY_DIR }}
            
            # (Opsional) Backup file konfigurasi penting jika ada perubahan
            # cp docker-compose.yml docker-compose.yml.bak
            
            # Pull image Docker terbaru dari n8nio/n8n
            docker-compose pull
            
            # Restart container dengan konfigurasi baru (jika ada perubahan di .yml)
            # -d = run in detached mode (background)
            docker-compose up -d
            
            echo "Update n8n selesai! Cek status..."
            docker ps -a | grep n8n
