name: Deploy Aplikasi ke VPS

# Kontrol kapan workflow ini akan berjalan
on:
  push:
    # Hanya berjalan saat ada push ke branch 'main'
    branches:
      - main
      
  # Memberikan opsi untuk menjalankan workflow secara manual dari tab Actions
  workflow_dispatch:

jobs:
  deploy:
    # Runner yang akan menjalankan job ini (GitHub-hosted runner)
    runs-on: ubuntu-latest
    
    steps:
      # ----------------------------------------------------
      # 1. Checkout Kode
      # ----------------------------------------------------
      - name: Checkout Kode
        uses: actions/checkout@v4
        # Catatan: Jika Anda ingin menggunakan SSH key saat checkout,
        # Anda perlu menambahkan step konfigurasi SSH key.

      # ----------------------------------------------------
      # 2. Sinkronisasi File (Deployment)
      # ----------------------------------------------------
      # Menggunakan action SCP (Secure Copy) untuk menyalin file
      - name: Sinkronisasi File ke VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          # Kredensial VPS (diambil dari GitHub Secrets)
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          
          # Sumber: Seluruh konten repositori (kecuali yang ada di .gitignore)
          source: "." 
          
          # Tujuan: Direktori di VPS tempat kode akan diletakkan
          target: ${{ secrets.DEPLOY_DIR }}
          
          # Flag SCP: Menghapus file di VPS yang tidak ada di repo (opsional, hati-hati!)
          # overwrite: true 

      # ----------------------------------------------------
      # 3. Jalankan Perintah Deployment (Opsional)
      # ----------------------------------------------------
      # Menggunakan action SSH untuk menjalankan perintah di VPS setelah file tersalin
      - name: Jalankan Perintah Setelah Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22 
          # Daftar perintah yang akan dieksekusi di VPS
          script: |
            echo "Deployment Selesai. Menjalankan perintah pasca-deploy..."
            
            # Pindah ke direktori deployment
            cd ${{ secrets.DEPLOY_DIR }}
            
            # Ganti perintah di bawah sesuai kebutuhan aplikasi Anda (contoh: PHP/Node.js)
            # Contoh 1: Install dependencies Node.js
            # npm install --production
            
            # Contoh 2: Restart service PM2
            # pm2 restart nama-aplikasi 
            
            # Contoh 3: Restart Nginx
            # sudo systemctl restart nginx
            
            echo "Perintah pasca-deploy selesai."
