name: RDP_DEBIAN_STYLE_TAILSCALE

on:
  push:
    # Workflow ini akan berjalan setiap kali ada push ke branch 'main'
    branches:
      - main
  # Memberikan opsi untuk menjalankan workflow secara manual dari tab Actions
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Deploy via SSH
        # Menggunakan action pihak ketiga yang populer untuk SSH deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Port SSH, default-nya adalah 22
          port: 22 
          # Perintah yang akan dijalankan di VPS setelah koneksi SSH dibuat
          script: |
            echo "Memulai deployment..."
            
            # Pindah ke direktori deployment
            cd ${{ secrets.DEPLOY_DIR }}
            
            # Pull kode terbaru dari GitHub
            # Pastikan Git sudah diinisialisasi di direktori ini
            git pull origin main
            
            # Lakukan langkah-langkah tambahan spesifik untuk aplikasi Anda (contoh):
            # 1. Install dependencies (jika ada, misal Node.js atau PHP)
            # npm install
            # composer install --no-dev --optimize-autoloader
            
            # 2. Build assets (jika ada)
            # npm run build
            
            # 3. Migrasi database (jika ada)
            # php artisan migrate --force
            
            # 4. Restart service aplikasi Anda (misal menggunakan PM2 atau Systemd)
            # pm2 restart nama-aplikasi
            # sudo systemctl restart nama-service
            
            echo "Deployment selesai!"
